- name: upgrade and  update packages
  become: true
  apt: 
   update_cache: yes

- name: move artifact to /tmp
  copy:
    src: ~/project/artifact.tar.gz
    dest: /tmp
    mode: 0777

- name: init new directory
  file:
    path: ~/src
    state: directory

- name: extract artifact to src
  unarchive:
    src: /tmp/artifact.tar.gz
    dest: .
    remote_src: yes

- name: ans start app
  become: true
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start
