- name: upgrade and  update packages
  become: true
  apt: 
   update_cache: yes

- name: move artifact to /tmp
  copy:
    src: ~/project/artifact.tar.gz
    dest: /tmp
    mode: 0777

- name: init new directory
  file:
    path: ~/src
    state: directory

- name: extract artifact to src
  unarchive:
    src: /tmp/artifact.tar.gz
    dest: ~/src
    remote_src: yes

- name: install node dependencies
  command: npm i 
  args:
    chdir: ~/src

- name: ans start app
  command: pm2 start main.js
  args:
    chdir: ~/src/dist
